#ifndef _PUNKTD_CONSTS_H_
#define _PUNKTD_CONSTS_H_

#define SHOWCASE_SIMPLE_FORMATTER_ID 0
#define SHOWCASE_SLIDER_FORMATTER_ID 1
#define SHOWCASE_SLIDER_304_224_FORMATTER_ID 2

#define EMPTY_PLACE 0

#define OZON_ADVID "ozon"
#define WIKIMART_ADVID "wikimart"

#define CAMPAIGN_MODE_STUB 0
#define CAMPAIGN_MODE_STANDART 1
#define CAMPAIGN_MODE_CUSTOM 2

#endif
